# Generated by Django 5.1 on 2024-09-17 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserDeviceModel',
            new_name='UserDevice',
        ),
    ]
