# Generated by Django 5.1 on 2024-09-17 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0004_alter_userdevice_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdevice',
            name='user',
            field=models.CharField(default='admin', max_length=100),
        ),
    ]
