# Generated by Django 5.1 on 2024-10-16 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0005_alter_userdevice_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idpelanggan', models.CharField(max_length=8)),
                ('necode', models.CharField(max_length=10)),
                ('namapelanggan', models.CharField(max_length=255)),
                ('tanggalinstalasi', models.DateField()),
                ('ipremote', models.CharField(max_length=15)),
                ('portwinbox', models.IntegerField(blank=True, null=True)),
                ('portssh', models.IntegerField(blank=True, null=True)),
                ('portapi', models.IntegerField(blank=True, null=True)),
                ('portweb', models.IntegerField(blank=True, null=True)),
                ('iplinkmain', models.CharField(max_length=15)),
                ('iplinkbackup', models.CharField(max_length=15)),
                ('iptambahan', models.TextField(blank=True, null=True)),
                ('parentrouter', models.CharField(max_length=255)),
                ('jenispaket', models.CharField(choices=[('Dedicated', 'dedicated'), ('Upto', 'upto'), ('Bhome', 'bhome'), ('Konekyu', 'konekyu')], default='bhome', max_length=100)),
                ('bwupload', models.FloatField()),
                ('bwdownload', models.FloatField()),
                ('aktivasibtools', models.CharField(choices=[('Ya', 'ya'), ('Tidak', 'tidak'), ('Tidak Ada Akses', 'tidak ada akses'), ('Perangkat Milik Client', 'perangkat milik client')], default='tidak', max_length=100)),
                ('connectto', models.CharField(max_length=15)),
                ('onuid', models.IntegerField(blank=True, null=True)),
                ('portconnect', models.IntegerField(blank=True, null=True)),
                ('pop', models.CharField(max_length=255)),
                ('mrtg', models.CharField(choices=[('Ya', 'ya'), ('Tidak', 'tidak')], default='tidak', max_length=100)),
                ('nagios', models.CharField(choices=[('Ya', 'ya'), ('Tidak', 'tidak')], default='tidak', max_length=100)),
                ('smokeping', models.CharField(choices=[('Ya', 'ya'), ('Tidak', 'tidak')], default='tidak', max_length=100)),
                ('media', models.CharField(choices=[('Converter/SFP', 'converter/sfp'), ('ODP', 'odp'), ('LAN', 'lan'), ('Wireless', 'wireless')], default='tidak', max_length=100)),
                ('redamansignalawal', models.CharField(max_length=7)),
                ('remark', models.TextField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
