# Generated by Django 5.1 on 2024-10-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0006_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='connectto',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='idpelanggan',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='client',
            name='iplinkbackup',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='iplinkmain',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='ipremote',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='necode',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='client',
            name='redamansignalawal',
            field=models.CharField(max_length=10),
        ),
    ]
