# Generated by Django 5.1 on 2024-10-16 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0007_alter_client_connectto_alter_client_idpelanggan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='connectto',
            field=models.CharField(max_length=100),
        ),
    ]
