# Generated by Django 5.1 on 2024-10-16 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0008_alter_client_connectto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='iplinkbackup',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='iplinkmain',
            field=models.CharField(max_length=100),
        ),
    ]
