# Generated by Django 5.1 on 2024-10-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0010_odp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odp',
            name='portRemaining',
            field=models.IntegerField(default=16),
        ),
        migrations.AlterField(
            model_name='odp',
            name='statusOpname',
            field=models.CharField(choices=[('Done', 'done'), ('-', '-')], default='tidak', max_length=100),
        ),
    ]
