# Generated by Django 5.1 on 2024-10-16 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0011_alter_odp_portremaining_alter_odp_statusopname'),
    ]

    operations = [
        migrations.AddField(
            model_name='odp',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
