# Generated by Django 5.1 on 2024-10-16 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0012_odp_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odp',
            name='statusOpname',
            field=models.CharField(choices=[('Done', 'done'), ('-', '-')], default='-', max_length=100),
        ),
    ]
