# Generated by Django 5.1 on 2024-10-16 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0014_rename_segmen_odp_segmen_odp_tanggalinstalasi'),
    ]

    operations = [
        migrations.AddField(
            model_name='odp',
            name='total_port',
            field=models.IntegerField(default=16),
        ),
    ]
