# Generated by Django 5.1 on 2024-10-20 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0015_odp_total_port'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pop', models.CharField(max_length=100)),
                ('deviceId', models.CharField(max_length=100)),
                ('installedDate', models.DateField()),
                ('remoteAddress', models.CharField(max_length=100)),
                ('addtionalIp', models.CharField(max_length=100)),
                ('portWinbox', models.IntegerField(default=8291)),
                ('portSsh', models.IntegerField(default=22)),
                ('portApi', models.IntegerField(default=8728)),
                ('portWeb', models.IntegerField(default=80)),
                ('layer', models.CharField(choices=[('BGP', 'bgp'), ('Core', 'core'), ('QRP', 'qrp'), ('BHome', 'bhome'), ('Konekyu', 'konekyu'), ('Distribution', 'distribution'), ('Access', 'access')], default='Access', max_length=15)),
                ('routerFirewall', models.CharField(choices=[('Ya', 'ya'), ('Tidak', 'tidak')], default='Tidak', max_length=6)),
                ('role', models.CharField(max_length=100)),
                ('frequency', models.IntegerField(default=5000)),
                ('channelBand', models.CharField(choices=[('5Ghz-A', '5ghz-a'), ('5Ghz-Only-N', '5ghz-only-n'), ('5Ghz-A/N', '5ghz-a/n'), ('5Ghz-A/N/AC', '5ghz-a/n/ac'), ('5Ghz-Only-AC', '5ghz-only-ac'), ('5Ghz-N/AC', '5ghz-n/ac'), ('-', '-')], default='-', max_length=100)),
                ('channelWidth', models.CharField(choices=[('20Mhz', '20mhz'), ('40Mhz', '40mhz'), ('80Mhz', '80mhz'), ('20/40Mhz EC', '20/40mhz ec'), ('20/40Mhz CE', '20/40mhz ce'), ('20/40Mhz XX', '20/40mhz xx'), ('20/40/80Mhz CEEE', '20/40/80mhz ceee'), ('20/40/80Mhz ECEE', '20/40/80mhz ecee'), ('20/40/80Mhz EECE', '20/40/80mhz eece'), ('20/40/80Mhz EEEC', '20/40/80mhz eeec'), ('20/40/80Mhz XXXX', '20/40/80mhz xxxx'), ('-', '-')], default='-', max_length=100)),
                ('signal', models.CharField(max_length=10)),
                ('sn', models.CharField(max_length=100)),
                ('os', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('watt', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Active', 'active'), ('Idle', 'idle')], default='idle', max_length=7)),
                ('remark', models.TextField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
