# Generated by Django 5.1 on 2024-10-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0017_alter_device_watt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdevice',
            name='group',
            field=models.CharField(choices=[('Read', 'read'), ('Write', 'write'), ('Full', 'full')], default='read', max_length=100),
        ),
    ]
