# Generated by Django 5.1 on 2024-10-22 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0018_alter_userdevice_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='deviceOs',
            field=models.CharField(default='RouterOs', max_length=100),
            preserve_default=False,
        ),
    ]
