# Generated by Django 5.1 on 2024-10-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0019_client_deviceos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='frequency',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('Active', 'active'), ('Idle', 'idle')], default='Active', max_length=7),
        ),
    ]
